// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blhkytwedpmyqwwbhprq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsaGt5dHdlZHBteXF3d2JocHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTA3MTcsImV4cCI6MjA1Nzk4NjcxN30.cRAq8OZHHoRAx76oT4riKCAP8WojYjnfk3ULrnevuvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a single client - no need for admin client anymore since RLS is disabled
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Keep the adminSupabase export for backward compatibility so we don't break existing code
export const adminSupabase = supabase;
